name: CI/CD Pipeline  

on: # hangi olaylarla tetikleneceğini sıralamak için 
  push: # değişiklik yapıldığında bir yerden diğer yere aktarıldığında tetiklenir
    branches: # yukarıdaki push gerçekleştiğinde hangi dalın etkileneceği seçilir. 
      - main # yukarıdaki push gerçekleştiğinde main tetiklenir ve iş akışı tetiklenir

jobs: # işlemlerimizin başladığı kısım yapıalcak işleri tanımlarız 
  build: 
    runs-on: self-hosted

    steps: # işlemlerimize başlarken her bir adımı buranın altında yapacağız
    # burada kodların alınmasını sağlıyoruz devamında uygulayacağımız adımlar bu kod ile işlem yapacak2
    - name: Checkout Code
      uses: actions/checkout@v2

    #- name: Set up Python
    #  uses: actions/setup-python@v2
    
    - name: Install Trivy
      run: |
          set -e
          # Diğer apt-get süreçlerinin kilidi tutup tutmadiğini kontrol et
          while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do 
            echo "Başka bir apt-get süreci kilidi serbest birakana kadar bekliyorum..."
            sleep 5
          done
          
          # Eğer kilit dosyasi hala varsa temizleyin
          sudo rm -f /var/lib/dpkg/lock-frontend
          sudo rm -f /var/cache/apt/archives/lock
          sudo rm -f /var/lib/dpkg/lock

          # Kurulum işlemini devam ettir
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo systemctl enable --now snapd.socket
          sudo snap install trivy
          sudo snap refresh trivy
      
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    
    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/myimage:${{ github.sha }}"
        docker build -t $IMAGE_TAG . 
        docker push $IMAGE_TAG

    - name: Run Trivy Scan 
      run: |
       
        trivy image --db-repository public.ecr.aws/aquasecurity/trivy-db:2 "${{ secrets.DOCKER_USERNAME }}/myimage:${{ github.sha }}"
    
    - name: AWS connect etme
      run: |
        hostname && ip r 
        docker stop $(docker ps -q)
        docker rm $(docker ps -a -q)
        docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/myimage:${{ github.sha }}

